### PR TITLE
Make the 'Return to Yar' quest fail on daybreak to match the behaviour of 'Get the PDA' quest and Yar's description of it

### PR DESCRIPTION
**Pull request by SurDno**
Fix for #7.

### CODE REVIEW

**Comment by Decane** [comment]
@SurDno Why has a spurious newline character been added to the end of each file? If it's your text editor doing that automatically, please configure it not to - it introduces a spurious diff into every file you edit that doesn't originally have a newline before end-of-file. (GSC did not consistently write POSIX-compliant text files.)

Your changes look otherwise sound.

**Comment by SurDno** [comment]
All of these pull requests have been done through GitHub online editor. I might switch to GitHub Desktop and some sort of local text editor.

**Comment by SurDno** [comment]
Yeah, I tried [reimplementing](https://github.com/SurDno/SRP/commit/d57d1429ce30f5bdfcdee73f0abeb0171931059b) the same change with Notepad++ and local GitHub Desktop and it worked perfectly, without end-of-the-line changes. I'll push these changes to 'yar' repository now.

**Comment by Decane** [comment]
Thanks - merged. :)

Just needs readme entries, but I'll handle those.

**Comment by SurDno** [comment]
Can you, if possible, port it to Decane/SRP-Lite as well?

**Pull request merged**
