### PR TITLE
Remove 'relationship = enemy' from Agroprom squad description

### LINKED ISSUE #33: Bandit squads on Agroprom are always enemies
There are two bandit squads on Agroprom, that sometimes send bonus squads to capture loners' base. In vanilla they could've been neutral when you have more than average reputation with bandits, but in SRP, for some reason, they shoot me no matter what my reputation is:

image

This screenshot shows that I'm friends with bandits, but more than that, I'm also a part of their ranks:

image

That's why they give me quests on clearing their road, that are very tough to complete, knowing that both sides are constantly shooting me and I should not kill half of them.

### PR DESCRIPTION
**Pull request by SurDno**
Since you did not close the issue with nofix tag yet, I believe you have intention on changing this. :)

This fixes #33

### CODE REVIEW

**Comment by SurDno** [comment]
Okay, seems like I had to do a separate branch for this. Now there are eight commits instead of one.

**Comment by SurDno** [comment]
I don't like the way I did this. I'll redo in a separate branch. Sorry.

**Comment by Decane** [comment]
@SurDno For future reference, there is no need to worry about the number of commits. I'll squash all of them into a single commit on merge anyway.

**Comment by SurDno** [comment]
That was not the only problem. I was not able to create a branch for other issues as well, because then it would copy all changed files. And also my fork was ~40 commits behind your master branch...

**Pull request closed without merging**
