### PR TITLE
Removed missing texture entries from external.ltx

### PR DESCRIPTION
**Pull request by SurDno**
I wrote a simple script to check which textures are not used. This was done mainly seeking for cut content but, as it turned out, there was very little stuff that could be somewhat interesting, so I decided to clean up the file instead.

### CODE REVIEW

**Comment by Decane** [comment]
Would you mind posting the code you used to determine which textures are unused? The list produced by the following command on my computer suggests you may have deleted a bit too much:
```
...\textures>for /f "usebackq delims=" %l in ("C:\Program Files (x86)\Deep Silver\S.T.A.L.K.E.R. - Clear Sky\gamedata\configs\external.ltx") do @(if exist %l.* echo %l)
```
For example, "fx\fx_wood_fire_bump" has been deleted, despite being referenced by fx\fx_wood_fire.thm, which in turn I believe the game reads to find the bump map to use for fx_wood_fire.dds.

**Comment by SurDno** [comment]
I wrote a simple Python script:
`import os
import sys

# We read the original file
with open("L:/3795/gamedata/configs/external.ltx", 'r') as file_in:
    lines = file_in.readlines()
    file_in.close()

# Rewrite file
with open("L:/3795/gamedata/configs/external.ltx", "w") as file_temp:
    for line in lines:
        if os.path.isfile('L:/3795/gamedata/textures/' + line[:-1] + '.dds'):
            file_temp.write(line)
    file_temp.close()

os.system('pause')`

**Comment by Decane** [comment]
>I'll have to check how exactly the engine deals with the list entries to know whether it makes sense to have non-texture files in there.

I checked. Only .dds files are matched against the entries in external.ltx. However...

The LOD for a texture is determined by iterating over every list entry in external.ltx and checking if the entry is a **substring** of the texture's relative path (e.g. "act\act_arm_1_bump.dds"). So even if e.g. "act\act_controller2" were missing from the list, act\act_controller2.dds would still get LOD-reduced (at below-max settings) because "act\act_controller" is in the list and is a substring of "act\act_controller2.dds".

This isn't a problem as long as every texture that _shouldn't_ get LOD-reduced starts with a path that's not listed in external.ltx. But it can cause bugs if ever that's not the case. We also have to be careful when removing an entry that no texture implicitly depends on it for LOD reduction due to that texture lacking its own entry. I've found that terrain\terrain_mp_limansk_mask.dds _does_ depend in this way on one of the entries you removed: "terrain\terrain_mp_limansk". The way to fix it is to add an explicit "terrain\terrain_mp_limansk_mask" entry to the list.

**Comment by Decane** [comment]
>The way to fix it is to add an explicit "terrain\terrain_mp_limansk_mask" entry to the list.

@SurDno Are you happy to make this change?

**Comment by SurDno** [comment]
Yeah, of course? I think I made the pull request free to edit by the repo owner if I have not messed anything up.

**Comment by Decane** [comment]
@SurDno After mulling over this, I think I'm going to simply replace the texture listing in external.ltx with a listing of texture sub-directories, like this:
```
[reduce_lod_texture_list]
act\
artifact\
...
```
That way, there is less hard-coding and any textures that were mistakenly omitted from the vanilla listing ([there are several](https://github.com/Decane/SRP/files/4840500/not-lod-reduced.log)) will be included by virtue of their relative path substring-matching one of the sub-directories in the list.

I'll include the pruned external.ltx in a future commit alongside other optimizations.

**Comment by Decane** [comment]
For posterity, I generated the list of textures that are not LOD-reduced in vanilla with the following Batch script:
```
@echo off

setlocal EnableDelayedExpansion

set "UNPACKER_FOLDER=C:\Program Files (x86)\Deep Silver\S.T.A.L.K.E.R. - Clear Sky\unpacker"
set "TEXTURES_FOLDER=%UNPACKER_FOLDER%\CS unpacked - anims, meshes, shaders, sounds, textures\textures"

pushd "%TEXTURES_FOLDER%"

for /f "delims=" %%l in ('dir *.dds /b /s') do (
	call :print_if_not_reduced "%%l"
)

popd

exit /b 0

:print_if_not_reduced (
	set "X=%~1"
	set "X=!X:%TEXTURES_FOLDER%\=!"
	set "X=!X:.dds=!"
	findstr /B /C:"%X%" "%UNPACKER_FOLDER%\CS unpacked - configs, scripts, spawns\configs\external.ltx" > NUL || echo %X%
	exit /b
)
```

**Pull request closed without merging**
